export const ADD_GOAL ='ADD_GOAL'
export const UPDATE_GOAL = 'UPDATE_GOAL'
export const DELETE_GOAL = 'DELETE_GOAL'
export const ADD_GOAL_TODO = 'ADD_GOAL_TODO'
export const UPDATE_GOAL_TODO = 'UPDATE'
